### ISSUE TITLE
Cars dataset

### ISSUE THREAD

**Issue by enkeejunior1** [kyrie-23/linear_task_arithmetic#1]
Thank you for your work.

I was wondering if you could tell me where to download the Stanford Cars dataset? It seems that the [URL](https://pytorch.org/vision/main/generated/torchvision.datasets.StanfordCars.html) used in the original code is no longer working.

I apologize in advance if this question is too basic.

**Comment by kyrie-23** [comment]
Hi, thanks for following, you may have a try at https://www.kaggle.com/datasets/cyizhuo/stanford-cars-by-classes-folder.

**Comment by enkeejunior1** [comment]
Thank you for your reply.
I found this link very helpful. If anyone is struggling with this problem, definitely check out this one.

https://github.com/pytorch/vision/issues/7545#issuecomment-1631441616

**Comment by kyrie-23** [comment]
Thanks for sharing!
